name: Monitoring Scripts

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Aave script
        run: |
          cd aave && python main.py && cd ..
        env:
          TELEGRAM_BOT_TOKEN_AAVE: ${{ secrets.TELEGRAM_BOT_TOKEN_AAVE }}
          TELEGRAM_CHAT_ID_AAVE: ${{ secrets.TELEGRAM_CHAT_ID_AAVE }}
          PROVIDER_URL: ${{ secrets.PROVIDER_URL }}
          PROVIDER_URL_MAINNET: ${{ secrets.PROVIDER_URL_MAINNET }}
          PROVIDER_URL_ARBITRUM: ${{ secrets.PROVIDER_URL_ARBITRUM }}
          PROVIDER_URL_OPTIMISM: ${{ secrets.PROVIDER_URL_OPTIMISM }}
      - name: Run Spark script
        run: |
          cd spark && python main.py && cd ..
        env:
          TELEGRAM_BOT_TOKEN_SPARK: ${{ secrets.TELEGRAM_BOT_TOKEN_AAVE }}
          TELEGRAM_CHAT_ID_SPARK: ${{ secrets.TELEGRAM_CHAT_ID_AAVE }}
          PROVIDER_URL_MAINNET: ${{ secrets.PROVIDER_URL_MAINNET }}
      - name: Run Compound script
        run: |
          cd compound && python main.py && cd ..
        env:
          TELEGRAM_BOT_TOKEN_COMP: ${{ secrets.TELEGRAM_BOT_TOKEN_COMP }}
          TELEGRAM_CHAT_ID_COMP: ${{ secrets.TELEGRAM_CHAT_ID_COMP }}
          PROVIDER_URL: ${{ secrets.PROVIDER_URL }}
          PROVIDER_URL_MAINNET: ${{ secrets.PROVIDER_URL_MAINNET }}
          PROVIDER_URL_ARBITRUM: ${{ secrets.PROVIDER_URL_ARBITRUM }}
          PROVIDER_URL_OPTIMISM: ${{ secrets.PROVIDER_URL_OPTIMISM }}
      - name: Run Lido Matic script
        run: cd lido/stmatic && python main.py && cd ../..
        env:
          TELEGRAM_BOT_TOKEN_LIDO: ${{ secrets.TELEGRAM_BOT_TOKEN_LIDO }}
          TELEGRAM_CHAT_ID_LIDO: ${{ secrets.TELEGRAM_CHAT_ID_LIDO }}
          PROVIDER_URL: ${{ secrets.PROVIDER_URL }}
          PROVIDER_URL_MAINNET: ${{ secrets.PROVIDER_URL_MAINNET }}
      - name: Run Lido Ethereum script
        run: cd lido/steth && python main.py && cd ../..
        env:
          TELEGRAM_BOT_TOKEN_LIDO: ${{ secrets.TELEGRAM_BOT_TOKEN_LIDO }}
          TELEGRAM_CHAT_ID_LIDO: ${{ secrets.TELEGRAM_CHAT_ID_LIDO }}
          PROVIDER_URL_MAINNET: ${{ secrets.PROVIDER_URL_MAINNET }}
      - name: Run Stargate script
        run: cd stargate && python main.py && cd ..
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PROVIDER_URL: ${{ secrets.PROVIDER_URL }}
          PROVIDER_URL_ARBITRUM: ${{ secrets.PROVIDER_URL_ARBITRUM }}
